version: '2'
services:
  # 名称服务，充当路由，即项目配置连接这个服务地址
  namesrv:
    image: rocketmqinc/rocketmq
    container_name: rmqnamesrv
    ports:
      - 9876:9876
    volumes:
      - /home/soft/rocketmq/logs:/home/rocketmq/logs
      - /home/soft/rocketmq/store:/home/rocketmq/store
    command: sh mqnamesrv
  # 代理服务，单节点模式
  broker:
    image: rocketmqinc/rocketmq
    container_name: rmqbroker
    ports:
      - 10909:10909
      - 10911:10911
      - 10912:10912
    volumes:
      - /home/soft/rocketmq/logs:/home/rocketmq/logs
      - /home/soft/rocketmq/store:/home/rocketmq/store
      - /home/soft/rocketmq/conf/broker.conf:/opt/rocketmq-4.4.0/conf/broker.conf
    # 这里采用docker内部网络连接，【services:ports】
    #command: sh mqbroker -n namesrv:9876
    command: sh mqbroker -n namesrv:9876 -c ../conf/broker.conf
    depends_on:
      - namesrv
    environment:
      - JAVA_HOME=/usr/lib/jvm/jre
  # 网页端控制台，是个springboot项目
  console:
    image: styletang/rocketmq-console-ng
    container_name: rocketmq-console-ng
    ports:
      - 8087:8080
    depends_on:
      - namesrv
    environment:
      - JAVA_OPTS= -Dlogging.level.root=info   -Drocketmq.namesrv.addr=rmqnamesrv:9876 
      - Dcom.rocketmq.sendMessageWithVIPChannel=false