version: '3'
services:
  minio:
    image: minio/minio:RELEASE.2021-05-18T00-53-28Z              # 最新镜像`minio/minio:latest`
    container_name: minio                                        # 容器名为'minio'
    restart: always                                              # 指定容器退出后的重启策略为始终重启
    volumes:                                                     # 数据卷挂载路径设置,将本机目录映射到容器目录
      - "./minio/data:/data"
      - "./minio/minio:/minio"
      - "./minio/config:/root/.minio"
    environment:                                          # 设置环境变量,相当于docker run命令中的-e
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
      MINIO_PROMETHEUS_AUTH_TYPE: "public"
      MINIO_ACCESS_KEY: "minio"                           # 登录账号
      MINIO_SECRET_KEY: "yh111111"                        # 登录密码
    command: server /data
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    ports:
      - "9001:9000"
      - "42330:42330"
