version: '3'

networks:
  esnet:
    driver: bridge

services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:6.8.12
    environment:
      TZ: Asia/Shanghai
      # 开发环境
      discovery.type: "single-node"
    ports:
      - 9200:9200
      - 9300:9300
    user: root
    networks:
      - esnet
  # 可视化管理平台
  elasticsearch-head:
    container_name: elasticsearch-head
    image: mobz/elasticsearch-head:5-alpine
    ports:
      - 9400:9100
    networks:
      - esnet
