version: '3'

networks:
  esnet:
    # 引用上面ELK相同网络
    external: truee

# 部署后配置修改，参考：http://huhuhan.github.io/blog/views/db/elasticsearch.html#elasticsearch-head
services:
  # 可视化管理平台
  elasticsearch-head:
    container_name: elasticsearch-head
    image: mobz/elasticsearch-head:5-alpine
    ports:
      - 9400:9100
    networks:
      - esnet

