version: '3'

services:
  activemq:
    # 容器名
    container_name: activemq
    # 重启策略: 容器退出时总是重启容器
    restart: always
    # 构建镜像名称，没有build属性默认从远程仓库获取
    image: webcenter/activemq
    environment:
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
      ACTIVEMQ_ADMIN_LOGIN: admin      # 登录账号
      ACTIVEMQ_ADMIN_PASSWORD: admin   # 登录密码
      ACTIVEMQ_CONFIG_MINMEMORY: 512   # M
      ACTIVEMQ_CONFIG_MAXMEMORY: 2048
    ports:
      # 服务器端口
      - 61616:61616
      # 网页端口
      - 8161:8161

#  admin:admin admin #管理员权限
#  user:user user #用户权限