version: '3'
services:
  mysql:
    network_mode: "bridge"
    environment:
      MYSQL_ROOT_PASSWORD: "yh!"
    image: "mysql:5.7.26"
    container_name: mysql
    restart: always
    volumes:
      - /sdb1/mysql/data:/var/lib/mysql
      - /sdb1/mysql/config/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    ports:
      - "8306:3306"