version: '3'
services:
  mysql:
    network_mode: "bridge"
    environment:
      MYSQL_ROOT_PASSWORD: "yh!"
    image: "mysql:5.7.26"
    container_name: mysql
    restart: always
    volumes:
      - /opt/docker-mysql/var/lib/mysql:/var/lib/mysql
      - /opt/docker-mysql/config/my.cnf:/etc/mysql/my.cnf
      - /opt/docker-mysql/config/conf.d/conf.d:/etc/mysql/conf.d
    ports:
      - "8206:3306"