version: '3'

networks:
  agilebpm:
    driver: bridge

# 开源项目，官网：http://www.agilebpm.cn/
services:
  agilebpm-source:
    # 构建是开源版本
    image: huhuhan/agilebpm:source
    container_name: agilebpm-source
    environment:
      TZ: Asia/Shanghai
    # 挂载配置文件application.yml
    volumes:
      - /YH/config:/usr/bpm-config
    # 构建的内部端口是8866
    ports:
      - 8866:8866
    networks:
      - agilebpm
